az login --service-principal -u http://azure-cli-2021-05-21-14-08-57 -p kiS6pNh7lIneNkxx_vwhftL.gldXP~ri5q -t 72f988bf-86f1-41af-91ab-2d7cd011db47

az account set --subscription "Anilkumarr-Microsoft Azure Internal Consumption"

az group create --name myResourceGroup --location westus2
az provider show -n Microsoft.OperationsManagement -o table
az provider show -n Microsoft.OperationalInsights -o table
az provider register --namespace Microsoft.OperationsManagement
az provider register --namespace Microsoft.OperationalInsights
az aks create --resource-group myResourceGroup --name myAKSCluster --node-count 1 --enable-addons monitoring --generate-ssh-keys
